services:
    frontend:
        build:
            context: ./frontend
        ports:
            - "3000:3000"
        depends_on:
            - backend
        environment:
            - NEXT_PUBLIC_API_URL=http://localhost:8080
    
    backend:
        build:
            context: ./backend
        ports:
            - "8080:8080"
        volumes:
            - ./backend/database.db:/app/database.db 
        environment:
            - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/database.db